### PR TITLE
Add spec file for RPM packaging

### PR DESCRIPTION
**Pull request by fepitre**
In case you would be interested, I've created a spec file for RPM packaging. I've tested under Fedora and I'm going to create a Fedora COPR repository too. It would be great to bump your current older version 0.6.0 to something like 0.6.1. In the spec, I used 0.6.0 as reference but I used the master branch for testing.

### CODE REVIEW

**Comment by fepitre** [comment]
Here is the repo: https://copr.fedorainfracloud.org/coprs/fepitre/xfce4-i3/

**Comment by acrisci** [comment]
I'm looking at doing a new release pretty soon.

**Comment by mnemitz** [comment]
Thanks for this! I'm looking into doing the same for OpenSUSE, will also make use of this spec, and link to the repo when it's done

**Comment by fepitre** [comment]
@mnemitz: I just enabled build on OpenSUSE 15.1, 15.2 and Tumbleweed on my COPR repo, it's building fine as is. Do you mind to test the package under OpenSUSE?

**Comment by mnemitz** [comment]
@fepitre Oh I see, didn't realize COPR integrated with OpenSUSE (this is my first encounter with it). I'll gladly try it out and let you know if there's any issue. Thanks!

**Comment by fepitre** [comment]
Sure. Depending on what @acrisci would prefer, I could keep maintaining a separate COPR including this package only or if he want to do it himself, it's fine and probably more suitable. In both cases, no problem for helping in the package side.

**Comment by fepitre** [comment]
@mnemitz: in case you are interested and would give it a try too, on my COPR repo I built xfce4-i3-workspaces-plugin for OpenSUSE too :)

**Comment by mnemitz** [comment]
@fepitre Definitely! I've added the repository, but I noticed that only the package for i3ipc-glib is included (even after refreshing). Perhaps it's just due to a delay in COPR or something, I don't know.

I'm currently running Tumbleweed, but I can test it all Leap as well later on.

**Comment by fepitre** [comment]
@mnemitz: my bad I launched the build  twice for i3ipc-glib instead of the plugin. I'll launch the build for the plugin.

**Comment by fepitre** [comment]
The build does not pass due to missing 'libxcb' https://download.copr.fedorainfracloud.org/results/fepitre/xfce4-i3/opensuse-tumbleweed-x86_64/01407575-xfce4-i3-workspaces-plugin/builder-live.log.gz. It's weird as it's the result of  the test transaction in i3ipc-glib that you succeeded to install?

**Comment by mnemitz** [comment]
Yeah I noticed that too and have been researching it a bit. It looks like libxcb is still in Factory at the moment: https://build.opensuse.org/package/show/openSUSE:Factory/libxcb

But then I thought, wait: I was able to build from source and run all this previously on the same system, so the library is clearly in the standard repos somewhere, then I discovered this:
https://software.opensuse.org/package/libxcb1

It's named libxcb1 instead of libxcb. Is it possible to change the spec for the OpenSUSE package to depend on libxcb1 instead of libxcd?

**Comment by fepitre** [comment]
@mnemitz yes it's possible to have conditional package depending on distro. I'll do that in the afternoon.

**Comment by fepitre** [comment]
Ok we have greenlights on builds for both components meaning you can install both :)

**Comment by mnemitz** [comment]
Thanks @fepitre! Just installed successfully :) This made my day!

**Comment by fepitre** [comment]
@acrisci: any new on merging this PR/bumping the version too?

**Comment by acrisci** [comment]
Here's the new release: https://github.com/altdesktop/i3ipc-glib/releases/tag/v1.0.1

**Comment by fepitre** [comment]
@acrisci: I've rebased and bump the version into the spec. Not tested the installation but the build is good: https://copr.fedorainfracloud.org/coprs/fepitre/xfce4-i3/build/1600193/. Thank you.

**Comment by acrisci** [comment]
:+1:

**Pull request merged**
